export const ADD_BUN = 'ADD_BUN';
export const ADD_OTHER_INGREDIENT = 'ADD_OTHER_INGREDIENT';
export const DELETE_OTHER_INGREDIENT = 'DELETE_OTHER_INGREDIENT';
export const SWAP_INGREDIENT = 'SWAP_INGREDIENT';